// Contiene las traducciones (ES/EN) y lógica de cambio de idioma.

const translations = {
    es: {
        and: "y",
        with: "con",
        jan: "Enero",
        feb: "Febrero",
        march: "Marzo",
        apr: "Abril",
        may: "Mayo",
        june: "Junio",
        july: "Julio",
        aug: "Agosto",
        sept: "Septiembre",
        oct: "Octubre",
        nov: "Noviembre",
        dec: "Diciembre",
        title_a: "Analista y Científico de Datos",
        title_b: "Desarrollador de IA y Redes Neuronales",
        airborne_a: '"Ningún obstáculo será tan grande que no pueda superarlo."',
        airborne_b: "Espíritu de superación del Ideario Paracaidista",
        about_button: "Sobre mí",
        education_button: "Educación",
        experience_button: "Experiencia",
        projects_button: "Proyectos",
        contact_button: "Contacto",
        language_button: "ES",
        language_button_es: "Español",
        language_button_en: "Inglés",
        about_a: "Soy una persona seria, trabajadora y resolutiva, con más de 8 años de experiencia en bases de datos y análisis.",
        about_b: "En los últimos años he decidido dar un paso más en mi desarrollo profesional, ampliando mis conocimientos hacia el análisis de datos avanzado, la creación de modelos de Inteligencia Artificial y el dominio de lenguajes de programación como Java, Python, R, SQL y HTML.",
        about_c: "Mi objetivo es combinar mi experiencia en gestión de datos con las herramientas más actuales de la analítica y la IA para generar soluciones eficientes y de valor en entornos empresariales.",
        about_skills: "Habilidades técnicas",
        about_programming: "Lenguajes de Programación",
        about_ai_data: "Inteligencia Artificial - Análisis de datos",
        about_databases: "Bases de datos",
        about_frontend: "Lenguajes de Marcado y FrontEnd",
        about_advanced: "Avanzado",
        about_interm_advanc: "Intermedio - Avanzado", 
        about_intermediate: "Intermedio",
        about_languages: "Idiomas",
        about_es: " Español: ",
        about_en: " Inglés: ",
        about_jp: " Japonés: ",
        about_native: "Nativo ",
        about_b2: "Intermedio-Avanzado - B2 ",
        about_n5: "Básico - N5 ",
        about_aptitudes: "Aptitudes",
        about_teamwork: "Trabajo en equipo",
        about_communication: "Comunicación",
        about_resolution: "Resolución de problemas",
        about_adapt: "Adaptabilidad",
        about_fastlearn: "Aprendizaje continuo",
        about_results: "Orientación a resultados",
        about_process: "Optimización de procesos",
        education_master_datascience: "Máster en Data Science y Business Analytics",
        competencies: "Competencias",
        mastercomp_a: "orientados a Inteligencia Artificial",
        mastercomp_b1: "Machine Learning",
        mastercomp_b2: "supervisado y no supervisado",
        mastercomp_b3: " ",
        mastercomp_c: "Estadística",
        mastercomp_d: "aplicada al análisis de datos",
        mastercomp_e: "Modelización predictiva",
        mastercomp_f: "Visualización de datos",
        mastercomp_g: "con librerías de Python",
        mastercomp_h1: "Bases de datos",
        mastercomp_h2: " ",
        mastercomp_i: "ficheros, API y web scraping",
        mastercomp_j: "Procesos ETL",
        mastercomp_k: "y automatización de flujos de datos",
        mastercomp_l: "y toma de decisiones basada en datos",
        education_dam: "FPGS en Desarrollo de Aplicaciones Multiplataforma",
        dam_a: "Programación orientada a objetos",
        dam_b: "Desarrollo de aplicaciones para entornos",
        dam_c: "y Escritorio",
        dam_d: "Bases de datos relacionales",
        dam_e: "lenguaje",
        dam_f: "Gestión de bases de datos",
        dam_g: "Desarrollo web",
        dam_h: "Diseño de interfaces",
        dam_i: "y usabilidad",
        dam_j: "Integración de servicios web",
        dam_k1: "consumo de",
        dam_k2: "APIs REST",
        dam_k3: " ",
        dam_l: "Control de versiones",
        dam_m: "Pruebas de software",
        dam_n: "depuración de código",
        dam_o: "Gestión de proyectos",
        dam_p1: "metodologías",
        dam_p2: "ágiles",
        dam_p3: " ",
        mba_a: "Dirección estratégica",
        mba_b: "y análisis competitivo",
        mba_c: "Gestión financiera",
        mba_d: "análisis de inversiones",
        mba_e1: "Marketing",
        mba_e2: "estratégico y digital",
        mba_e3: " ",
        mba_f: "Gestión de proyectos",
        mba_g: "y liderazgo de equipos",
        mba_h: "Recursos Humanos",
        mba_i: "y desarrollo organizacional",
        mba_j: "Operaciones",
        mba_k: "y optimización de procesos",
        mba_l1: "Contabilidad",
        mba_l2: "financiera y de costes",
        mba_l3: " ",
        mba_m: "Negociación",
        mba_n: "y toma de decisiones",
        mba_o: "Emprendimiento",
        mba_p: "y desarrollo de modelos de negocio",
        ade: "Licenciatura en Administración y Dirección de Empresas",
        unisev: "Universidad de Sevilla",
        seville: "Sevilla",
        nonregulated_training: "Formación no reglada",
        trading: "Formación en inversión y trading de Futuros y CFDs",
        openwebinar: "Formación en OpenWebinar",
        show_courses: "Mostrar cursos",
        hours: "horas",
        opweb_a: "para principiantes e intermedio",
        opweb_b: "desde cero",
        opweb_c: "Maquetación Web y Responsive Web Design",
        opweb_d: "Metodologías Ágiles",
        opweb_e1: " ",
        opweb_e2: "Técnico",
        opweb_f: "y patrones de diseño",
        opweb_g1: "Técnicas de",
        opweb_g2: " ",
        administrative: "Administrativo",
        army: "Ejército de Tierra",
        cefot: "Centro de Formación de Tropa nº2 (CEFOT-2)",
        tasks: "Cometidos",
        cefot_a: "Desarrollo de pequeños scripts para el procesamiento y limpieza de datos administrativos, facilitando la generación de informes y estadísticas académicas.",
        cefot_b: "Creación de plantillas automatizadas para reportes periódicos, mejorando la consistencia y reduciendo el tiempo de elaboración.",
        cefot_c: "Participación en proyectos de digitalización y organización de expedientes mediante el diseño de estructuras de bases de datos relacionales.",
        cefot_d: "Colaboración en la implementación de sistemas de control académico apoyados en métricas de rendimiento y dashboards interactivos.",
        cefot_e: "Exploración de técnicas básicas de análisis de datos y modelos predictivos orientados a detectar patrones de asistencia, rendimiento o necesidades de formación.",
        cefot_f: "Uso de consultas SQL y herramientas de análisis para obtener información clave y apoyar la toma de decisiones en la planificación académica.",
        coder: "Desarrollador de software",
        practicas_fpgs: "Prácticas tuteladas FPGS",
        inetum_a: "Diseño y desarrollo de aplicaciones a medida utilizando tecnologías front-end y back-end según los requerimientos del cliente.",
        inetum_b: "Participación en metodologías ágiles (SCRUM) colaborando con analistas y testers.",
        inetum_c: "Refactorización de código y aplicación de principios SOLID para mejorar la mantenibilidad de los proyectos.",
        inetum_d: "Automatización de procesos y pruebas unitarias para garantizar la calidad del software entregado.",
        inetum_e: "Documentación técnica de proyectos y soporte a usuarios en la fase de implementación.",
        soldier: "Soldado de Infantería",
        bripac_vi: 'Brigada Paracaidista "Almogávares VI"',
        bripac_a: "Trabajo en equipo en entornos de alta exigencia, fomentando la cooperación, la confianza y la comunicación efectiva.",
        bripac_b: "Gestión del estrés y capacidad de mantener la concentración en situaciones críticas.",
        bripac_c: "Disciplina y compromiso con el cumplimiento de objetivos, garantizando consistencia y responsabilidad en los proyectos.",
        bripac_d: "Adaptación rápida a entornos cambiantes y aprendizaje continuo para afrontar nuevos desafíos.",
        bripac_e: "Búsqueda de soluciones creativas ante limitaciones de recursos, habilidad clave para la programación y la optimización de procesos.",
        bripac_f: "Capacidad de liderazgo en la coordinación de pequeños equipos, potenciando el rendimiento colectivo y la toma de decisiones.",
        project_a: "MODELOS PREDICTIVOS DEL PRECIO DE LAS CRIPTOMONEDAS",
        project_a1: "Estudio comparativo de diferentes modelos predictivos con distintos niveles de complejidad para evaluar su viabilidad en la predicción del precio de las criptomonedas, tomando como referencia el caso de Bitcoin.",
        project_a2: "Python · Scikit-learn · TensorFlow (Keras) · XGBoost · Red Neuronal Recurrente (RNN) · Support Vector Regressor (SVR)",
        project_b: "APRENDIZAJE POR REFUERZO: BANDIDO MULTIBRAZO",
        project_b1: "Estudio aplicado del método del Bandido Multibrazo orientado a la optimización del contenido mostrado en una web, analizando el impacto de distintas imágenes sobre los visitantes. Mediante técnicas de aprendizaje por refuerzo, se determina de forma dinámica qué opción maximiza el número de clics, equilibrando exploración y explotación para mejorar progresivamente el rendimiento del sitio.",
        project_b2: "Python · Matplotlib · Aprendizaje por refuerzo · Bandido Multibrazo",
        project_c: "ESTIMACIÓN DEL PRECIO DE UN VEHÍCULO",
        project_c1: "Desarrollo de un modelo predictivo para estimar el precio de un vehículo de segunda mano a partir de sus características. Incluye un análisis exploratorio(EDA) y la aplicación de algoritmos de aprendizaje supervisado.",
        project_c2: "Python · Scikit-learn · XGBoost · Seaborn",
        project_d: "RESOLUCIÓN DE CUESTIONES MEDIANTE EL USO DE PYSPARK",
        project_d1: "Aplicación de la interfaz PySpark para resolver diversas cuestiones relacionadas con clientes y contratos de una compañía de telecomunicaciones, combinando operaciones distribuidas y consultas SQL.",
        project_d2: "Python · PySpark · SQL · DataBricks",
        project_e: "COMPARACIÓN DE MODELOS DE CLASIFICACIÓN",
        project_e1: "Comparación de distintos modelos de clasificación supervisada — regresión logística, red neuronal y random forest — con el objetivo de predecir la probabilidad de compra de los clientes en una web. Incluye un análisis exploratorio(EDA) y la evaluación de métricas de rendimiento para identificar el modelo con mejor capacidad predictiva.",
        project_e2: "Python · Scikit-learn · TensorFlow (Keras) · Seaborn · Matplotlib · Regresión Logística · Red Neuronal · Random Forest",
        project_f: "MODELO DE REGRESIÓN LINEAL CON REGULARIZACIONES DE RIDGE Y LASSO",
        project_f1: "Análisis de una muestra de salarios de profesores universitarios en Estados Unidos. Incluye un estudio exploratorio de los datos(EDA), el entrenamiento de un modelo de regresión lineal con regularizaciones Ridge y Lasso, y la evaluación de la normalidad de los residuos del modelo resultante.",
        project_f2: "R · dplyr · ggplot2 · glmnet",
        project_g: "BASE DE DATOS ORIENTADA A GRAFOS: NEO4J",
        project_g1: "Uso de la base de datos orientada a grafos (GDB) Neo4J y del lenguaje de consulta Cypher para analizar las relaciones entre personas contagiadas y no contagiadas por COVID-19, mediante la creación y exploración de nodos y aristas.",
        project_g2: "Neo4J · Cypher · GDB",
        project_h: "BASE DE DATOS NOSQL: MONGODB",
        project_h1: "Utilización de la base de datos NoSQL MongoDB y su lenguaje MongoDB Shell en un entorno Linux para la resolución de consultas relacionadas con mediciones de sensores IoT de temperatura, humedad y emisiones de CO₂.",
        project_h2: "MongoDB · Linux · MongoDB Shell · NoSQL",
        data_extract: "Extracción de datos",
        eda_analysis: "Análisis EDA",
        ia_model: "Modelo",
        multiarmed_bandit: "Bandido Multibrazo",
        eda_model: "EDA y Modelo",
        tables: "Preparación de tablas",
        quest_resolution: "Resolución de cuestiones",
        email_text: "Correo electrónico",
        email_title: "Haz clic para enviar correo",
        copied: "¡Copiado!",
        email_clipboard_title: "Haz clic para copiar la dirección de correo",
        linkedin_profile: "Perfil de LinkedIn",
        linkedin_title: "Haz clic para ver mi perfil en LinkedIn"
    },
    en: {
        and: "and",
        with: "with",
        jan: "January",
        feb: "February",
        march: "March",
        apr: "April",
        may: "May",
        june: "June",
        july: "July",
        aug: "August",
        sept: "September",
        oct: "October",
        nov: "November",
        dec: "December",
        title_a: "Data Analyst and Scientist",
        title_b: "AI and Neural Network Developer",
        airborne_a: '"No obstacle will be so great that it cannot be overcome."',
        airborne_b: "Spirit of perseverance from the Paratrooper’s Creed",
        about_button: "About me",
        education_button: "Education",
        experience_button: "Experience",
        projects_button: "Projects",
        contact_button: "Contact",
        language_button: "EN",
        language_button_es: "Spanish",
        language_button_en: "English",
        about_a: "I am a serious, hardworking, and decisive person with over 8 years of experience in databases and analytics.",
        about_b: "In recent years, I've decided to take a further step in my professional development, expanding my knowledge into advanced data analysis, the creation of artificial intelligence models, and mastering programming languages ​​such as Java, Python, R, SQL, and HTML.",
        about_c: "My goal is to combine my experience in data management with the latest analytics and AI tools to generate efficient and valuable solutions in business environments.",
        about_skills: "Technical skills",
        about_programming: "Programming Languages",
        about_ai_data: "Artificial Intelligence - Data Analysis",
        about_databases: "Databases",
        about_frontend: "Markup Languages ​​and Front-End",
        about_advanced: "Advanced",
        about_interm_advanc: "Intermediate - Advanced",
        about_intermediate: "Intermediate",
        about_languages: "Languages",
        about_es: " Spanish: ",
        about_en: " English: ",
        about_jp: " Japanese: ",
        about_native: "Native ",
        about_b2: "Intermediate-Advanced - B2 ",
        about_n5: "Basic - N5 ",
        about_aptitudes: "Aptitudes",
        about_teamwork: "Teamwork",
        about_communication: "Communication",
        about_resolution: "Problem-solving",
        about_adapt: "Adaptability",
        about_fastlearn: "Continuous learning",
        about_results: "Results-oriented",
        about_process: "Process optimization",
        education_master_datascience: "Master's Degree in Data Science and Business Analytics",
        competencies: "Competencies",
        mastercomp_a: "for Artificial Intelligence",
        mastercomp_b1: " ",
        mastercomp_b2: "Supervised and unsupervised",
        mastercomp_b3: "Machine Learning",
        mastercomp_c: "Statistics",
        mastercomp_d: "applied to data analysis",
        mastercomp_e: "Predictive Modeling",
        mastercomp_f: "Data Visualization",
        mastercomp_g: "with Python libraries",
        mastercomp_h1: " ",
        mastercomp_h2: "Databases",
        mastercomp_i: "Files, APIs, and web scraping",
        mastercomp_j: "ETL Processes",
        mastercomp_k: "and dataflow automation",
        mastercomp_l: "and data-driven decision-making",
        education_dam: "Associate's Degree in Cross-Platform Application Development",
        dam_a: "Object-Oriented programming",
        dam_b: "Application development for",
        dam_c: "and Desktop environments",
        dam_d: "Relational databases",
        dam_e: " ",
        dam_f: "Database management",
        dam_g: "Web development",
        dam_h: "Interface design",
        dam_i: "and usability",
        dam_j: "Web service integration",
        dam_k1: " ",
        dam_k2: "REST API",
        dam_k3: "consumption",
        dam_l: "Version control",
        dam_m: "Software testing",
        dam_n: "code debugging",
        dam_o: "Project management",
        dam_p1: " ",
        dam_p2: "Agile",
        dam_p3: "Methodologies",
        mba_a: "Strategic management",
        mba_b: "and competitive analysis",
        mba_c: "Financial management",
        mba_d: "investment analysis",
        mba_e1: " ",
        mba_e2: "Strategic and digital",
        mba_e3: "marketing",
        mba_f: "Project management",
        mba_g: "and team leadership",
        mba_h: "Human resources",
        mba_i: "and organizational development",
        mba_j: "Operations",
        mba_k: "and process optimization",
        mba_l1: " ",
        mba_l2: "Financial and cost",
        mba_l3: "accounting",
        mba_m: "Negotiation",
        mba_n: "and decision-making",
        mba_o: "Entrepreneurship",
        mba_p: "and business model development",
        ade: "Bachelor's Degree in Business Administration and Management",
        unisev: "University of Seville",
        seville: "Seville",
        nonregulated_training: "Non-regulated training",
        trading: "Futures and CFD Investment and Trading Training",
        openwebinar: "OpenWebinar Training",
        show_courses: "Show courses",
        hours: "hours",
        opweb_a: "for Beginners and Intermediate",
        opweb_b: "from scratch",
        opweb_c: "Web Layout and Responsive Web Design",
        opweb_d: "Agile Methodologies",
        opweb_e1: "Technical",
        opweb_e2: " ",
        opweb_f: "and Design Patterns",
        opweb_g1: " ",
        opweb_g2: "Techniques",
        administrative: "Administrative",
        army: "Spanish Army",
        cefot: "Recruit Training Center No. 2 (CEFOT-2)",
        tasks: "Tasks",
        cefot_a: "Development of short scripts for processing and cleansing administrative data, facilitating the generation of academic reports and statistics.",
        cefot_b: "Creation of automated templates for periodic reports, improving consistency and reducing preparation time.",
        cefot_c: "Participation in digitization and file organization projects through the design of relational database structures.",
        cefot_d: "Collaboration in the implementation of academic control systems supported by performance metrics and interactive dashboards.",
        cefot_e: "Exploration of basic data analysis techniques and predictive models aimed at detecting patterns in attendance, performance, or training needs.",
        cefot_f: "Use of SQL queries and analysis tools to obtain key information and support decision-making in academic planning.",
        coder: "Software developer",
        practicas_fpgs: "Supervised Associate Degree Internships",
        inetum_a: "Design and development of custom applications using front-end and back-end technologies according to client requirements.",
        inetum_b: "Participation in agile methodologies (SCRUM) collaborating with analysts and testers.",
        inetum_c: "Code refactoring and application of SOLID principles to improve project maintainability.",
        inetum_d: "Process automation and unit testing to ensure the quality of the delivered software.",
        inetum_e: "Technical project documentation and user support during the implementation phase.",
        soldier: "Infantryman",
        bripac_vi: 'Parachute Brigade "Almogávares VI"',
        bripac_a: "Teamwork in highly demanding environments, fostering cooperation, trust, and effective communication.",
        bripac_b: "Stress management and the ability to maintain focus in critical situations.",
        bripac_c: "Discipline and commitment to meeting objectives, ensuring consistency and accountability in projects.",
        bripac_d: "Rapid adaptation to changing environments and continuous learning to face new challenges.",
        bripac_e: "Search for creative solutions in the face of resource constraints, a key skill for programming and process optimization.",
        bripac_f: "Leadership ability in coordinating small teams, enhancing collective performance and decision-making.",
        project_a: "CRYPTOCURRENCY PRICE PREDICTIVE MODELS",
        project_a1: "Comparative study of different predictive models with varying levels of complexity to evaluate their viability in predicting cryptocurrency prices, using Bitcoin as a reference.",
        project_a2: "Python · Scikit-learn · TensorFlow (Keras) · XGBoost · Recurrent Neural Network (RNN) · Support Vector Regressor (SVR)",
        project_b: "REINFORCEMENT LEARNING: MULTI-ARM BANDIT",
        project_b1: "Applied study of the Multi-Arm Bandit method aimed at optimizing the content displayed on a website, analyzing the impact of different images on visitors. Using reinforcement learning techniques, it is dynamically determined which option maximizes the number of clicks, balancing exploration and exploitation to progressively improve the site's performance.",
        project_b2: "Python · Matplotlib · Reinforcement Learning · Multi-Arm Bandit",
        project_c: "VEHICLE PRICE ESTIMATION",
        project_c1: "Development of a predictive model to estimate the price of a used vehicle based on its characteristics. Includes exploratory analysis (EDA) and the application of supervised learning algorithms.",
        project_c2: "Python · Scikit-learn · XGBoost · Seaborn",
        project_d: "QUESTION SOLVING USING PYSPARK",
        project_d1: "Application of the PySpark interface to resolve various questions related to clients and contracts of a telecommunications company, combining distributed operations and SQL queries.",
        project_d2: "Python · PySpark · SQL · DataBricks",
        project_e: "COMPARISON OF CLASSIFICATION MODELS",
        project_e1: "Comparison of different supervised classification models — logistic regression, neural network, and random forest — with the goal of predicting customers' purchase probability on a website. Includes exploratory data analysis (EDA) and evaluation of performance metrics to identify the model with the best predictive capacity.",
        project_e2: "Python · Scikit-learn · TensorFlow (Keras) · Seaborn · Matplotlib · Logistic Regression · Neural Network · Random Forest",
        project_f: "LINEAR REGRESSION MODEL WITH RIDGE AND LASSO REGULARIZATIONS",
        project_f1: "Analysis of a sample of university professor salaries in the United States. Includes an exploratory data analysis (EDA), training of a linear regression model with Ridge and Lasso regularizations, and evaluation of the normality of the resulting model's residuals.",
        project_f2: "R · dplyr · ggplot2 · glmnet",
        project_g: "GRAPH DATABASE: NEO4J",
        project_g1: "Using the graph database (GDB) Neo4J and the Cypher query language to analyze relationships between people infected with COVID-19 and those not infected by creating and exploring nodes and edges.",
        project_g2: "Neo4J · Cypher · GDB",
        project_h: "NOSQL DATABASE: MONGODB",
        project_h1: "Using the NoSQL database MongoDB and its MongoDB Shell language in a Linux environment to solve queries related to IoT sensor measurements of temperature, humidity, and CO₂ emissions.",
        project_h2: "MongoDB · Linux · MongoDB Shell · NoSQL",
        data_extract: "Data extraction",
        eda_analysis: "EDA Analysis",
        ia_model: "Model",
        multiarmed_bandit: "Multi-Armed Bandit",
        eda_model: "EDA and Model",
        tables: "Preparing Tables",
        quest_resolution: "Question Resolution",
        email_text: "Email",
        email_title: "Click to send Email",
        copied: "Copied!",
        email_clipboard_title: "Click to copy Email",
        linkedin_profile: "LinkedIn Profile",
        linkedin_title: "Click to go to my LinkedIn Profile"
    }
};


function setLanguage(lang) {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    // Traducción de atributos
    const attrElements = document.querySelectorAll("[data-i18n-title]");
    attrElements.forEach(el => {
        const key = el.getAttribute("data-i18n-title");
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute("title", translations[lang][key]);
        }
    });

    // Actualizar bandera del idioma
    const flagElement = document.getElementById("lang_flag");
    if (flagElement) {
        // Elimina clases anteriores
        flagElement.className = "";

        // Asigna la clase correspondiente según idioma
        if (lang === "es") {
            flagElement.classList.add("flag-icon", "flag-icon-es");
        } else if (lang === "en") {
            flagElement.classList.add("flag-icon", "flag-icon-gb");
        }
    }

    localStorage.setItem("selectedLang", lang);
}

// Guardar preferencia del usuario
window.addEventListener("DOMContentLoaded", () => {
    const lang = localStorage.getItem("selectedLang") || "es";
    setLanguage(lang);
});






